// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bus is the predicate function for bus builders.
type Bus func(*sql.Selector)

// Bus_driver is the predicate function for bus_driver builders.
type Bus_driver func(*sql.Selector)
