// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BusColumns holds the columns for the "bus" table.
	BusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "bus_name", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "is_delete", Type: field.TypeInt8, Default: 1},
	}
	// BusTable holds the schema information for the "bus" table.
	BusTable = &schema.Table{
		Name:       "bus",
		Columns:    BusColumns,
		PrimaryKey: []*schema.Column{BusColumns[0]},
	}
	// BusDriversColumns holds the columns for the "bus_drivers" table.
	BusDriversColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_name", Type: field.TypeString, Size: 25},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "is_delete", Type: field.TypeInt8, Default: 1},
		{Name: "user_age", Type: field.TypeInt8},
		{Name: "sex", Type: field.TypeBool},
		{Name: "career_age", Type: field.TypeInt8},
	}
	// BusDriversTable holds the schema information for the "bus_drivers" table.
	BusDriversTable = &schema.Table{
		Name:       "bus_drivers",
		Columns:    BusDriversColumns,
		PrimaryKey: []*schema.Column{BusDriversColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BusTable,
		BusDriversTable,
	}
)

func init() {
}
