// Code generated by ent, DO NOT EDIT.

package bus

import (
	"time"
)

const (
	// Label holds the string label denoting the bus type in the database.
	Label = "bus"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBusName holds the string denoting the bus_name field in the database.
	FieldBusName = "bus_name"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldIsDelete holds the string denoting the is_delete field in the database.
	FieldIsDelete = "is_delete"
	// Table holds the table name of the bus in the database.
	Table = "bus"
)

// Columns holds all SQL columns for bus fields.
var Columns = []string{
	FieldID,
	FieldBusName,
	FieldCreateTime,
	FieldUpdateTime,
	FieldUserID,
	FieldIsDelete,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BusNameValidator is a validator for the "bus_name" field. It is called by the builders before save.
	BusNameValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime time.Time
	// DefaultIsDelete holds the default value on creation for the "is_delete" field.
	DefaultIsDelete int8
)
