// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/HaleNing/bustrack/src/Model/ent/bus"
)

// BusCreate is the builder for creating a Bus entity.
type BusCreate struct {
	config
	mutation *BusMutation
	hooks    []Hook
}

// SetBusName sets the "bus_name" field.
func (bc *BusCreate) SetBusName(s string) *BusCreate {
	bc.mutation.SetBusName(s)
	return bc
}

// SetCreateTime sets the "create_time" field.
func (bc *BusCreate) SetCreateTime(t time.Time) *BusCreate {
	bc.mutation.SetCreateTime(t)
	return bc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (bc *BusCreate) SetNillableCreateTime(t *time.Time) *BusCreate {
	if t != nil {
		bc.SetCreateTime(*t)
	}
	return bc
}

// SetUpdateTime sets the "update_time" field.
func (bc *BusCreate) SetUpdateTime(t time.Time) *BusCreate {
	bc.mutation.SetUpdateTime(t)
	return bc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (bc *BusCreate) SetNillableUpdateTime(t *time.Time) *BusCreate {
	if t != nil {
		bc.SetUpdateTime(*t)
	}
	return bc
}

// SetUserID sets the "user_id" field.
func (bc *BusCreate) SetUserID(i int64) *BusCreate {
	bc.mutation.SetUserID(i)
	return bc
}

// SetIsDelete sets the "is_delete" field.
func (bc *BusCreate) SetIsDelete(i int8) *BusCreate {
	bc.mutation.SetIsDelete(i)
	return bc
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (bc *BusCreate) SetNillableIsDelete(i *int8) *BusCreate {
	if i != nil {
		bc.SetIsDelete(*i)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BusCreate) SetID(i int64) *BusCreate {
	bc.mutation.SetID(i)
	return bc
}

// Mutation returns the BusMutation object of the builder.
func (bc *BusCreate) Mutation() *BusMutation {
	return bc.mutation
}

// Save creates the Bus in the database.
func (bc *BusCreate) Save(ctx context.Context) (*Bus, error) {
	var (
		err  error
		node *Bus
	)
	bc.defaults()
	if len(bc.hooks) == 0 {
		if err = bc.check(); err != nil {
			return nil, err
		}
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = bc.check(); err != nil {
				return nil, err
			}
			bc.mutation = mutation
			if node, err = bc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			if bc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, bc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Bus)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from BusMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BusCreate) SaveX(ctx context.Context) *Bus {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BusCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BusCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BusCreate) defaults() {
	if _, ok := bc.mutation.CreateTime(); !ok {
		v := bus.DefaultCreateTime
		bc.mutation.SetCreateTime(v)
	}
	if _, ok := bc.mutation.UpdateTime(); !ok {
		v := bus.DefaultUpdateTime
		bc.mutation.SetUpdateTime(v)
	}
	if _, ok := bc.mutation.IsDelete(); !ok {
		v := bus.DefaultIsDelete
		bc.mutation.SetIsDelete(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BusCreate) check() error {
	if _, ok := bc.mutation.BusName(); !ok {
		return &ValidationError{Name: "bus_name", err: errors.New(`ent: missing required field "Bus.bus_name"`)}
	}
	if v, ok := bc.mutation.BusName(); ok {
		if err := bus.BusNameValidator(v); err != nil {
			return &ValidationError{Name: "bus_name", err: fmt.Errorf(`ent: validator failed for field "Bus.bus_name": %w`, err)}
		}
	}
	if _, ok := bc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Bus.create_time"`)}
	}
	if _, ok := bc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Bus.update_time"`)}
	}
	if _, ok := bc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Bus.user_id"`)}
	}
	if _, ok := bc.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "is_delete", err: errors.New(`ent: missing required field "Bus.is_delete"`)}
	}
	return nil
}

func (bc *BusCreate) sqlSave(ctx context.Context) (*Bus, error) {
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (bc *BusCreate) createSpec() (*Bus, *sqlgraph.CreateSpec) {
	var (
		_node = &Bus{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: bus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: bus.FieldID,
			},
		}
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.BusName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bus.FieldBusName,
		})
		_node.BusName = value
	}
	if value, ok := bc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bus.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := bc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bus.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := bc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: bus.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := bc.mutation.IsDelete(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: bus.FieldIsDelete,
		})
		_node.IsDelete = value
	}
	return _node, _spec
}

// BusCreateBulk is the builder for creating many Bus entities in bulk.
type BusCreateBulk struct {
	config
	builders []*BusCreate
}

// Save creates the Bus entities in the database.
func (bcb *BusCreateBulk) Save(ctx context.Context) ([]*Bus, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Bus, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BusCreateBulk) SaveX(ctx context.Context) []*Bus {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BusCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BusCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
