// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/HaleNing/bustrack/src/Model/ent/bus_driver"
	"github.com/HaleNing/bustrack/src/Model/ent/predicate"
)

// BusDriverDelete is the builder for deleting a Bus_driver entity.
type BusDriverDelete struct {
	config
	hooks    []Hook
	mutation *BusDriverMutation
}

// Where appends a list predicates to the BusDriverDelete builder.
func (bdd *BusDriverDelete) Where(ps ...predicate.Bus_driver) *BusDriverDelete {
	bdd.mutation.Where(ps...)
	return bdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bdd *BusDriverDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bdd.hooks) == 0 {
		affected, err = bdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BusDriverMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bdd.mutation = mutation
			affected, err = bdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bdd.hooks) - 1; i >= 0; i-- {
			if bdd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bdd *BusDriverDelete) ExecX(ctx context.Context) int {
	n, err := bdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bdd *BusDriverDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: bus_driver.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: bus_driver.FieldID,
			},
		},
	}
	if ps := bdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// BusDriverDeleteOne is the builder for deleting a single Bus_driver entity.
type BusDriverDeleteOne struct {
	bdd *BusDriverDelete
}

// Exec executes the deletion query.
func (bddo *BusDriverDeleteOne) Exec(ctx context.Context) error {
	n, err := bddo.bdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bus_driver.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bddo *BusDriverDeleteOne) ExecX(ctx context.Context) {
	bddo.bdd.ExecX(ctx)
}
