// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/HaleNing/bustrack/src/Model/ent/migrate"

	"github.com/HaleNing/bustrack/src/Model/ent/bus"
	"github.com/HaleNing/bustrack/src/Model/ent/bus_driver"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Bus is the client for interacting with the Bus builders.
	Bus *BusClient
	// Bus_driver is the client for interacting with the Bus_driver builders.
	Bus_driver *Bus_driverClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Bus = NewBusClient(c.config)
	c.Bus_driver = NewBus_driverClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Bus:        NewBusClient(cfg),
		Bus_driver: NewBus_driverClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Bus:        NewBusClient(cfg),
		Bus_driver: NewBus_driverClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Bus.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Bus.Use(hooks...)
	c.Bus_driver.Use(hooks...)
}

// BusClient is a client for the Bus schema.
type BusClient struct {
	config
}

// NewBusClient returns a client for the Bus from the given config.
func NewBusClient(c config) *BusClient {
	return &BusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bus.Hooks(f(g(h())))`.
func (c *BusClient) Use(hooks ...Hook) {
	c.hooks.Bus = append(c.hooks.Bus, hooks...)
}

// Create returns a builder for creating a Bus entity.
func (c *BusClient) Create() *BusCreate {
	mutation := newBusMutation(c.config, OpCreate)
	return &BusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Bus entities.
func (c *BusClient) CreateBulk(builders ...*BusCreate) *BusCreateBulk {
	return &BusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Bus.
func (c *BusClient) Update() *BusUpdate {
	mutation := newBusMutation(c.config, OpUpdate)
	return &BusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BusClient) UpdateOne(b *Bus) *BusUpdateOne {
	mutation := newBusMutation(c.config, OpUpdateOne, withBus(b))
	return &BusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BusClient) UpdateOneID(id int64) *BusUpdateOne {
	mutation := newBusMutation(c.config, OpUpdateOne, withBusID(id))
	return &BusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Bus.
func (c *BusClient) Delete() *BusDelete {
	mutation := newBusMutation(c.config, OpDelete)
	return &BusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BusClient) DeleteOne(b *Bus) *BusDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *BusClient) DeleteOneID(id int64) *BusDeleteOne {
	builder := c.Delete().Where(bus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BusDeleteOne{builder}
}

// Query returns a query builder for Bus.
func (c *BusClient) Query() *BusQuery {
	return &BusQuery{
		config: c.config,
	}
}

// Get returns a Bus entity by its id.
func (c *BusClient) Get(ctx context.Context, id int64) (*Bus, error) {
	return c.Query().Where(bus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BusClient) GetX(ctx context.Context, id int64) *Bus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BusClient) Hooks() []Hook {
	return c.hooks.Bus
}

// Bus_driverClient is a client for the Bus_driver schema.
type Bus_driverClient struct {
	config
}

// NewBus_driverClient returns a client for the Bus_driver from the given config.
func NewBus_driverClient(c config) *Bus_driverClient {
	return &Bus_driverClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bus_driver.Hooks(f(g(h())))`.
func (c *Bus_driverClient) Use(hooks ...Hook) {
	c.hooks.Bus_driver = append(c.hooks.Bus_driver, hooks...)
}

// Create returns a builder for creating a Bus_driver entity.
func (c *Bus_driverClient) Create() *BusDriverCreate {
	mutation := newBusDriverMutation(c.config, OpCreate)
	return &BusDriverCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Bus_driver entities.
func (c *Bus_driverClient) CreateBulk(builders ...*BusDriverCreate) *BusDriverCreateBulk {
	return &BusDriverCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Bus_driver.
func (c *Bus_driverClient) Update() *BusDriverUpdate {
	mutation := newBusDriverMutation(c.config, OpUpdate)
	return &BusDriverUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Bus_driverClient) UpdateOne(bd *Bus_driver) *BusDriverUpdateOne {
	mutation := newBusDriverMutation(c.config, OpUpdateOne, withBus_driver(bd))
	return &BusDriverUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Bus_driverClient) UpdateOneID(id int64) *BusDriverUpdateOne {
	mutation := newBusDriverMutation(c.config, OpUpdateOne, withBus_driverID(id))
	return &BusDriverUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Bus_driver.
func (c *Bus_driverClient) Delete() *BusDriverDelete {
	mutation := newBusDriverMutation(c.config, OpDelete)
	return &BusDriverDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Bus_driverClient) DeleteOne(bd *Bus_driver) *BusDriverDeleteOne {
	return c.DeleteOneID(bd.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *Bus_driverClient) DeleteOneID(id int64) *BusDriverDeleteOne {
	builder := c.Delete().Where(bus_driver.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BusDriverDeleteOne{builder}
}

// Query returns a query builder for Bus_driver.
func (c *Bus_driverClient) Query() *BusDriverQuery {
	return &BusDriverQuery{
		config: c.config,
	}
}

// Get returns a Bus_driver entity by its id.
func (c *Bus_driverClient) Get(ctx context.Context, id int64) (*Bus_driver, error) {
	return c.Query().Where(bus_driver.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Bus_driverClient) GetX(ctx context.Context, id int64) *Bus_driver {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Bus_driverClient) Hooks() []Hook {
	return c.hooks.Bus_driver
}
