// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/HaleNing/Ning_JobBoard/src/Model/ent/predicate"
	"github.com/HaleNing/Ning_JobBoard/src/Model/ent/user_job"
)

// UserJobQuery is the builder for querying User_job entities.
type UserJobQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.User_job
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserJobQuery builder.
func (ujq *UserJobQuery) Where(ps ...predicate.User_job) *UserJobQuery {
	ujq.predicates = append(ujq.predicates, ps...)
	return ujq
}

// Limit adds a limit step to the query.
func (ujq *UserJobQuery) Limit(limit int) *UserJobQuery {
	ujq.limit = &limit
	return ujq
}

// Offset adds an offset step to the query.
func (ujq *UserJobQuery) Offset(offset int) *UserJobQuery {
	ujq.offset = &offset
	return ujq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ujq *UserJobQuery) Unique(unique bool) *UserJobQuery {
	ujq.unique = &unique
	return ujq
}

// Order adds an order step to the query.
func (ujq *UserJobQuery) Order(o ...OrderFunc) *UserJobQuery {
	ujq.order = append(ujq.order, o...)
	return ujq
}

// First returns the first User_job entity from the query.
// Returns a *NotFoundError when no User_job was found.
func (ujq *UserJobQuery) First(ctx context.Context) (*User_job, error) {
	nodes, err := ujq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{user_job.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ujq *UserJobQuery) FirstX(ctx context.Context) *User_job {
	node, err := ujq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first User_job ID from the query.
// Returns a *NotFoundError when no User_job ID was found.
func (ujq *UserJobQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ujq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{user_job.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ujq *UserJobQuery) FirstIDX(ctx context.Context) int {
	id, err := ujq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single User_job entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one User_job entity is found.
// Returns a *NotFoundError when no User_job entities are found.
func (ujq *UserJobQuery) Only(ctx context.Context) (*User_job, error) {
	nodes, err := ujq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{user_job.Label}
	default:
		return nil, &NotSingularError{user_job.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ujq *UserJobQuery) OnlyX(ctx context.Context) *User_job {
	node, err := ujq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only User_job ID in the query.
// Returns a *NotSingularError when more than one User_job ID is found.
// Returns a *NotFoundError when no entities are found.
func (ujq *UserJobQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ujq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{user_job.Label}
	default:
		err = &NotSingularError{user_job.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ujq *UserJobQuery) OnlyIDX(ctx context.Context) int {
	id, err := ujq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of User_jobs.
func (ujq *UserJobQuery) All(ctx context.Context) ([]*User_job, error) {
	if err := ujq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ujq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ujq *UserJobQuery) AllX(ctx context.Context) []*User_job {
	nodes, err := ujq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of User_job IDs.
func (ujq *UserJobQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ujq.Select(user_job.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ujq *UserJobQuery) IDsX(ctx context.Context) []int {
	ids, err := ujq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ujq *UserJobQuery) Count(ctx context.Context) (int, error) {
	if err := ujq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ujq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ujq *UserJobQuery) CountX(ctx context.Context) int {
	count, err := ujq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ujq *UserJobQuery) Exist(ctx context.Context) (bool, error) {
	if err := ujq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ujq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ujq *UserJobQuery) ExistX(ctx context.Context) bool {
	exist, err := ujq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserJobQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ujq *UserJobQuery) Clone() *UserJobQuery {
	if ujq == nil {
		return nil
	}
	return &UserJobQuery{
		config:     ujq.config,
		limit:      ujq.limit,
		offset:     ujq.offset,
		order:      append([]OrderFunc{}, ujq.order...),
		predicates: append([]predicate.User_job{}, ujq.predicates...),
		// clone intermediate query.
		sql:    ujq.sql.Clone(),
		path:   ujq.path,
		unique: ujq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		JobID int64 `json:"job_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserJob.Query().
//		GroupBy(user_job.FieldJobID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ujq *UserJobQuery) GroupBy(field string, fields ...string) *UserJobGroupBy {
	grbuild := &UserJobGroupBy{config: ujq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ujq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ujq.sqlQuery(ctx), nil
	}
	grbuild.label = user_job.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		JobID int64 `json:"job_id,omitempty"`
//	}
//
//	client.UserJob.Query().
//		Select(user_job.FieldJobID).
//		Scan(ctx, &v)
func (ujq *UserJobQuery) Select(fields ...string) *UserJobSelect {
	ujq.fields = append(ujq.fields, fields...)
	selbuild := &UserJobSelect{UserJobQuery: ujq}
	selbuild.label = user_job.Label
	selbuild.flds, selbuild.scan = &ujq.fields, selbuild.Scan
	return selbuild
}

func (ujq *UserJobQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ujq.fields {
		if !user_job.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ujq.path != nil {
		prev, err := ujq.path(ctx)
		if err != nil {
			return err
		}
		ujq.sql = prev
	}
	return nil
}

func (ujq *UserJobQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*User_job, error) {
	var (
		nodes = []*User_job{}
		_spec = ujq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*User_job).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &User_job{config: ujq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ujq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ujq *UserJobQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ujq.querySpec()
	_spec.Node.Columns = ujq.fields
	if len(ujq.fields) > 0 {
		_spec.Unique = ujq.unique != nil && *ujq.unique
	}
	return sqlgraph.CountNodes(ctx, ujq.driver, _spec)
}

func (ujq *UserJobQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := ujq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (ujq *UserJobQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user_job.Table,
			Columns: user_job.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user_job.FieldID,
			},
		},
		From:   ujq.sql,
		Unique: true,
	}
	if unique := ujq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ujq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user_job.FieldID)
		for i := range fields {
			if fields[i] != user_job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ujq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ujq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ujq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ujq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ujq *UserJobQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ujq.driver.Dialect())
	t1 := builder.Table(user_job.Table)
	columns := ujq.fields
	if len(columns) == 0 {
		columns = user_job.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ujq.sql != nil {
		selector = ujq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ujq.unique != nil && *ujq.unique {
		selector.Distinct()
	}
	for _, p := range ujq.predicates {
		p(selector)
	}
	for _, p := range ujq.order {
		p(selector)
	}
	if offset := ujq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ujq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserJobGroupBy is the group-by builder for User_job entities.
type UserJobGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ujgb *UserJobGroupBy) Aggregate(fns ...AggregateFunc) *UserJobGroupBy {
	ujgb.fns = append(ujgb.fns, fns...)
	return ujgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ujgb *UserJobGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ujgb.path(ctx)
	if err != nil {
		return err
	}
	ujgb.sql = query
	return ujgb.sqlScan(ctx, v)
}

func (ujgb *UserJobGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ujgb.fields {
		if !user_job.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ujgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ujgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ujgb *UserJobGroupBy) sqlQuery() *sql.Selector {
	selector := ujgb.sql.Select()
	aggregation := make([]string, 0, len(ujgb.fns))
	for _, fn := range ujgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ujgb.fields)+len(ujgb.fns))
		for _, f := range ujgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ujgb.fields...)...)
}

// UserJobSelect is the builder for selecting fields of UserJob entities.
type UserJobSelect struct {
	*UserJobQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ujs *UserJobSelect) Scan(ctx context.Context, v any) error {
	if err := ujs.prepareQuery(ctx); err != nil {
		return err
	}
	ujs.sql = ujs.UserJobQuery.sqlQuery(ctx)
	return ujs.sqlScan(ctx, v)
}

func (ujs *UserJobSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := ujs.sql.Query()
	if err := ujs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
