// Code generated by ent, DO NOT EDIT.

package bus_driver

import (
	"time"
)

const (
	// Label holds the string label denoting the bus_driver type in the database.
	Label = "bus_driver"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldIsDelete holds the string denoting the is_delete field in the database.
	FieldIsDelete = "is_delete"
	// FieldUserAge holds the string denoting the user_age field in the database.
	FieldUserAge = "user_age"
	// FieldSex holds the string denoting the sex field in the database.
	FieldSex = "sex"
	// FieldCareerAge holds the string denoting the career_age field in the database.
	FieldCareerAge = "career_age"
	// Table holds the table name of the bus_driver in the database.
	Table = "bus_drivers"
)

// Columns holds all SQL columns for bus_driver fields.
var Columns = []string{
	FieldID,
	FieldUserName,
	FieldCreateTime,
	FieldUpdateTime,
	FieldIsDelete,
	FieldUserAge,
	FieldSex,
	FieldCareerAge,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime time.Time
	// DefaultIsDelete holds the default value on creation for the "is_delete" field.
	DefaultIsDelete int8
	// UserAgeValidator is a validator for the "user_age" field. It is called by the builders before save.
	UserAgeValidator func(int8) error
	// CareerAgeValidator is a validator for the "career_age" field. It is called by the builders before save.
	CareerAgeValidator func(int8) error
)
