// Code generated by ent, DO NOT EDIT.

package user_info

const (
	// Label holds the string label denoting the user_info type in the database.
	Label = "user_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldSalt holds the string denoting the salt field in the database.
	FieldSalt = "salt"
	// FieldPasswdHash holds the string denoting the passwd_hash field in the database.
	FieldPasswdHash = "passwd_hash"
	// Table holds the table name of the user_info in the database.
	Table = "user_infos"
)

// Columns holds all SQL columns for user_info fields.
var Columns = []string{
	FieldID,
	FieldUserName,
	FieldSalt,
	FieldPasswdHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// SaltValidator is a validator for the "salt" field. It is called by the builders before save.
	SaltValidator func(string) error
	// PasswdHashValidator is a validator for the "passwd_hash" field. It is called by the builders before save.
	PasswdHashValidator func(string) error
)
